name = "Zui & Nat"
author = "Zui"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fcec7d6bdd85cca552b7babd3a0f07fbcfcb943d6a667f5c94abbdb471dd4eba"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
