name = "Zui & Nat"
author = "Zui"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e6cac0cba9036ba948ff66546f8a8c8fb58eb084543e25f23ee08df61fe5499"

[versions]
fabric = "0.14.5"
minecraft = "1.18.2"
