name = "Cat"
author = "Zui"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc1ea2a6f5ded148fcf5db04ce052bedd97d3f294dc3340af2c64d0522fc408e"

[versions]
fabric = "0.14.19"
minecraft = "1.19.2"
