name = "Dynamic Surroundings"
filename = "DynamicSurroundings-Fabric-1.18.2-0.0.4.jar"
side = "client"

[download]
url = "https://raw.githubusercontent.com/fromatozui/minecraft-server-mods/main/external_mods/DynamicSurroundings-Fabric-1.18.2-0.0.4.jar"
hash-format = "sha256"
hash = "0b79f9b3fd7055d2ca4053bcadbb0a2243294f697ac689fd34f098848f861c96"