name = "OptiFabric"
filename = "optifabric-1.13.0.jar"
side = "client"

[download]
url = "https://edge.forgecdn.net/files/3717/575/optifabric-1.13.0.jar"
hash-format = "sha1"
hash = "7aad70d413df55472b545fbd615b928c06152469"

[update]
[update.curseforge]
file-id = 3717575
project-id = 322385
