name = "Optifine"
filename = "OptiFine_1.18.2_HD_U_H7.jar"
side = "client"

[download]
url = "https://raw.githubusercontent.com/fromatozui/minecraft-server-mods/main/external_mods/OptiFine_1.18.2_HD_U_H7.jar"
hash-format = "sha256"
hash = "79264fa2994e78a48321abe75191162290dcb6e9e307287eee60e53ff8962a99"